# Generated by Django 3.1.1 on 2020-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifytapahi', '0002_auto_20201118_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCodeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
